# Generated by Django 3.2.13 on 2022-11-20 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='hate_users',
            field=models.ManyToManyField(related_name='review_hate', to=settings.AUTH_USER_MODEL),
        ),
    ]
