# Generated by Django 3.2.13 on 2022-11-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20221121_2002'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watched_movies',
            field=models.ManyToManyField(related_name='watched_user', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_movies',
            field=models.ManyToManyField(related_name='like_user', to='movies.Movie'),
        ),
    ]
